
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=shop_cau_long_footstyle;encrypt=true;trustServerCertificate=true;
spring.datasource.username=sa
spring.datasource.password=223600
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true