spring.application.name=backend
server.port=${SERVER_PORT:8081}
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=shop_cau_long_footstyle;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=223600
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
spring.jackson.time-zone=Asia/Ho_Chi_Minh
app.upload-dir=${UPLOAD_DIR:uploads}
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
app.giam-gia.che-do-chong-dot=${GIAM_GIA_CHE_DO:MAX}
app.mail.from=${MAIL_FROM:}
app.mail.ten-cua-hang=FootStyle
